# CodeDeploy version
version: 0.0
# windows / linux type of deployment
os: linux
# copy all files to the instance
files:
  - source: /app/
    # Default NGINX location
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: deploy/scripts/install_dependencies.sh
      timeout: 60
      runas: root
    - location: deploy/scripts/start_server.sh
      timeout: 10
      runas: root

  ApplicationStop:
    - location: deploy/scripts/stop_server.sh
      timeout: 10
      runas: root
